<?php

 ?>

 <head>
   <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
   <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
   <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
   <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
   <link href="https://fonts.googleapis.com/css?family=Montserrat:400,500i,600,600i,700i,800,800i,900&display=swap" rel="stylesheet">
   <title>Alviva | Secure player information storage</title>
   <style>
   body, html {
     padding: 0;
     margin: 0;
     margin-left: 0%;
     font-family: "Montserrat";
   }

   h3 {
     margin-left: 5.3%;
   }

   .footer {
     position: fixed;
     bottom: 0;
     left: 0;
     width: 100%;
     background: #F5F5F5;
     height: 150;
     padding: 50;
     padding-left: 3%;
     padding-top: 30;
   }

   .nav {
     position: fixed;
     top: 70;
     right: 50;
     width: 30%;
     font-size: 25px
   }

   .hl {
     background-image: linear-gradient(#fff 60%, #FFFF00 55%);
     display: inline;
     font-weight: 600;
   }


   </style>

 </head>

 <body>
   <h1 style="font-weight: 900; margin-left: 3%; margin-top: 3%">alviva</h1>
   <br>
   <br>
   <h1 style="font-weight: 400; margin-left: 3%; margin-top: 4%">The <i class="hl">new standard</i> for how player<br>information is stored</h1>
   <br>
   <h4 style="margin-left: 3%; font-weight: 400;">Learn how Alviva securely encrypts and stores player<br>data online and can help you say goodbye<br>to tedious paperwork.</h4>
   <br>
   <br>
   <div class="btn-group" style="margin-left: 3%">
  <a href="#" class="btn btn-primary" style="border-radius: 0; width: 290;">alviva for <strong>clubs</strong> »</a>
  <a href="#" class="btn btn-success" style="margin-left: 10px; border-radius: 0; width: 290;">alviva for <strong>parents</strong> »</a>
</div>

<img src="iphone.png" style="position: fixed; bottom: 150; right: 25%; width: 600"></img>

<div class="nav">
  <a>product</a> <a style="margin-left: 20">pricing</a> <a style="margin-left: 20">support</a> <a href="login.php"><button type="button" class="btn btn-outline-primary" style="margin-left: 30; border-radius: 0;">access account</button></a>
</div>

<div class="footer">
  <div class="row" style="position: fixed; right: 15%">
    <div class="col-xs-6">
        <strong>clubs</strong> <br>
        <a>Tournament organization &raquo;</a><br>
        <a>Team link &raquo;</a>
    </div>
    <div class="col-xs-6" style="margin-left: 60">
        <strong>teams</strong><br>
        <a>Team portfolio &raquo;</a><br>
    </div>
    <div class="col-xs-6" style="margin-left: 70">
        <strong>parents</strong><br>
        <a>Update your child's information &raquo;</a><br>
        <a>Submit team change &raquo;</a><br>
        <a>
    </div>
</div>
</div>
 </body>
